feat: structure proposal
SlovakNationalGallery/atlas-frontend pull request #3
Opened 2023-10-27 14:33 UTC by mayoforkovic

2023-11-02 07:53 UTC, FrantisekMichalSebestyen requested changes

2023-11-02 09:14 UTC, mayoforkovic commented on src/components/interactions/InteractionStory.vue
> +            src="../../img/avatar-ester.png"
it was fixed in last PR

2023-11-02 12:06 UTC, igor-kamil approved these changes
Overall well done. I like the structure more. Also router-link looks nicer after this change. Works nicely... for me  good to go 🚀 
For the next time: use the task ID in the branch name (for syncing with jira).
Also it's always nice to write something in the PR overview 👀

2023-11-02 12:06 UTC, igor-kamil commented on .gitignore
> +/public/fonts/
I don't really mind. But I think it was not necessary to change this 😉

2023-11-02 12:06 UTC, igor-kamil commented on src/components/interactions/InteractionStory.vue
> +            src="../../img/avatar-ester.png"
confirmed 
https://github.com/SlovakNationalGallery/atlas-frontend/pull/5/commits/19e7083bad2aca5b67cc74b5f56da65248a975e0

2023-11-08 14:27 UTC, FrantisekMichalSebestyen approved these changes

2023-11-09 12:40 UTC, merged